[workspace]
members = ["crates/*"]

# Temporarily use object_store with the following fix until
# https://github.com/apache/arrow-rs/pull/3489 (commit id eae993) is released
# on crates.io (likley 0.5.4)
[patch.crates-io]
object_store = { git = "https://github.com/glaredb/arrow-rs.git", branch = "content-length" }
