[package]
name = "diststore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coretypes = {path = "../coretypes"}
fmtutil = {path = "../fmtutil"}
logutil = {path = "../logutil"}
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.0"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
tokio-serde = { version = "0.8", features = ["bincode"] }
async-trait = "0.1.56"
bincode = "1.3.3"
futures = "0.3.21"
bytes = "1.1"
foca = { version = "0.3", features = ["std", "tracing", "bincode-codec"] }
rand = "0.8"
