[package]
name = "sqlengine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coretypes = {path = "../coretypes"}
fmtutil = {path = "../fmtutil"}
logutil = {path = "../logutil"}
diststore = {path = "../diststore"}
sqlparser = "0.18.0"
thiserror = "1.0"
anyhow = "1.0"
bitvec = "1"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3.21"
async-trait = "0.1.56"

