[package]
name = "sqlengine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logutil = {path = "../logutil"}
lemur = {path = "../lemur"}
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.56"
futures = "0.3.21"
rand = "0.8"
parking_lot = "0.12.1"
sqlparser = "0.18.0"
