[package]
name = "glaredb"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "glaredb"
path = "src/bin/glaredb.rs"

[[bin]]
name = "glarec"
path = "src/bin/glarec.rs"

[dependencies]
coretypes = {path = "../coretypes"}
fmtutil = {path = "../fmtutil"}
logutil = {path = "../logutil"}
diststore = {path = "../diststore"}
sqlengine = {path = "../sqlengine"}
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
tokio-serde = { version = "0.8", features = ["bincode"] }
bincode = "1.3.3"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "3.2", features = ["derive"] }
log = "0.4.0"
futures = "0.3.21"
rustyline = "9.1.2"

